### ISSUE TITLE
Mariculture Overwriting ThermalExpansion Outputs!

### ISSUE THREAD

**Issue by Lanse505** [joshiejack/Mariculture#191]
Mods: 
Mariculture V.MARICULTURE-1.7.10-1.2.3D and 
Thermal Expansion V.THERMALEXPANSION-[1.7.10]4.0.0B5-13

Explenation:
Okey it's very simple, When you put a Empty bucket into a Fluid Transposer with Lava. When it's finished filling the bucket, instead of outputing a Bucket of Lava it seems to be replaced by Mariculture and it outputs a Nether droplet (Lava Droplet) instead. I think this might be a problem with the Nether Droplet replacing the Vanilla Lava Buckets output.

**Comment by joshiejack** [comment]
Useless droplets are added.
