### ISSUE TITLE
Fish config option request for Witchery mod spirit world compatibility

### ISSUE THREAD

**Issue by Zebia** [joshiejack/Mariculture#201]
This is a request for a config option that will disable the ability to get night fish in witchery's spirit world, for the purpose of those of us who want to breed fish in our world while maintaining the spirit worlds intended semi-impermeability to the transfer of items. 

Possible forms this feature could take are:
-disabling the ability to catch night fish in the spirit world
-a blacklist for catching certain kinds of fish in certain dimensions
-an option to disable the catching of night fish at night :P
-an option to change what products fish produce
-disabling the ability to catch fish in the spirit world

to give context to this request, witchery adds a dimension called the "Spirit World" (default dimension id -37) that you can only enter via going to "sleep" with the help of items added by the mod, upon entering the spirit world you leave all items with your "body" for when you "wake" and from then on maintain a separate inventory that is only used in the spirit world, only a few specific items are transferred when you transition between the worlds.More importantly the spirit world is identical to the overworld except endermen don't spawn, and thus enderpearls; and with them eye of ender,ender chests, and most mod obtainable methods of inter-dimensional item transport; are unobtainable in the spirit world.this makes it impossible to transfer items between other dimensions and the spirit world except for the aforementioned few specific items.however when mariculture is installed you can obtain live night fish in the spirit world, which produce resonant ender, and thus tesseracts, ender chests, and all mod added inter-dimensional item transport systems that require an ender pearl become obtainable.   

thank you for your time and this mod.

**Comment by joshiejack** [comment]
Will probably add some sort of filters if i do keep fish working the same in 2.0, Not gonna add for 1.0 though, so gonna close.
