### ISSUE TITLE
Generators not working

### ISSUE THREAD

**Issue by Garagoth** [joshiejack/Mariculture#202]
Hi,

I setup water tower, rotors, generator just as in image from in-game book.
Rotors are rotating, pressurized water rips holes from time to time in terrain, all looks fine...
However, I cannot seem to be able to connect any cable to generator nor bring up any GUI from it.
Also, it seems that generator registered "generator" as correct tool to remove it.

MC: 1.7.10
Mariculture: 1.2.3d
Forge: 1208

Regards,
Garagoth.

**Comment by joshiejack** [comment]
I know they work.
