### ISSUE TITLE
Mariculture anvil doesn't respond to leftclick with hammer

### ISSUE THREAD

**Issue by Lyneira** [joshiejack/Mariculture#212]
Problem: When a hammerable item is on the anvil (such as dandelion, aluminium block or an unworked pearl necklace crafted from wool and pearls)

Steps to reproduce:
* Create a new MultiMC instance, using 1.7.10 and latest forge version.
* Install Mariculture and Enchiridion off the minecraft forums thread.
* Start instance, create a new creative world.
* Get a dandelion and/or aluminium block from the creative menu.
* Get a mariculture anvil and blacksmith's hammer in the machines tab.
* Place anvil.
* /gamemode 0
* Put dandelion on anvil and hammer it
* Nothing happens... (same with the aluminium block)

Tested on a Windows 8.1 machine with Java 7 Update 72, and on a Windows 7 laptop with Java 7 Update 65. Same procedure also tested with the forge installer instead of MultiMC.

I was a bit hesitant to report this as an issue because I've seen it working in my WIP modpack before with the same mariculture version, but considering I can create the problem on a completely different machine with an install as vanilla as I can make it, I'm out of ideas on what it could be on my end.

**Comment by joshiejack** [comment]
You need 1xp in order to hammer anything.
