### ISSUE TITLE
erebus bug

### ISSUE THREAD

**Issue by THEVOLCO** [joshiejack/Mariculture#214]
hi, there is a bug with the erbus mod. when u try to enter the Erebus Dimension the game crashes. I first asked ganymedes01 (Erebus author) for help and then he told me that it´s your mod causing the Problem and that i should ask u.
here´s the Crash Report:

http://pastebin.com/YGyzf1rq

**Comment by joshiejack** [comment]
add the erebus dimension to the blacklist for dimensions in the config
