### ISSUE TITLE
Localization change

### ISSUE THREAD

**Issue by Adaptivity** [joshiejack/Mariculture#219]
For the proper translation in Russian I need different color names for "mariculture.lamps.format" string.

**Comment by joshiejack** [comment]
I'm not sure I understand? It uses the colours from mariculture.pearl.color.white etc

**Comment by Adaptivity** [comment]
Yes, it so. BUT I need to change ending of colors for mariculture.lamps.format.

**Comment by joshiejack** [comment]
Can you give me examples . I am so confused xD.

**Comment by Adaptivity** [comment]
White Pearl Block -> "Белый жемчужный блок" (In Russian)
White Neon Lamp -> "Белая неоновая лампа" (In Russian)
As you can see color words have different endings: "-ый" for block or brick, "-ая" for lamp.

**Comment by Adaptivity** [comment]
So, can you do this?

**Comment by joshiejack** [comment]
Something I'll keep in mind for the future, but right now... I'd rather just let 1.X pass on. I'll do it when I have a bunch of bugs to fix :P

**Comment by Adaptivity** [comment]
Ok. Will wait.

**Comment by joshiejack** [comment]
The way this will work it will look for a translation for

pearl.color.yellow.lamp
pearl.color.yellow.block
pearl.color.yellow.pearl
pearl.color.yellow.brick

and if it cannot find the relevant translation it will use the default of pearl.color.yellow
So feel free to add these translations. (They won't be in the english lang)

**Comment by Adaptivity** [comment]
Ok, thanks.

**Comment by joshiejack** [comment]
Will just wait on this, then I'll upload the new version.

**Comment by Adaptivity** [comment]
Few more requests for improving translation:
1) Pearls seems to be localized like: Color + mariculture.pearl. Can they use unique names? Like "mariculture.pearls.pearlwhite"?
2) Rings, Bracelets, Necklaces seems to be localized like: "Color" + Pearl + ring/bracelet/necklace. Can you add %s tag to item. name? I need swap item name with color and pearl.
Reopened for some time.

**Comment by Adaptivity** [comment]
About release... well, can we at least fix all missing names in en_US.lang? There a lot of them.

**Comment by joshiejack** [comment]
What ones?

**Comment by joshiejack** [comment]
As for the pearls you already have "mariculture.pearl.format" and then you can edit "mariculture.pearl.color.yellow.pearl" etc.

**Comment by Adaptivity** [comment]
I'll send a PR to fix missing names soon. Can you make something for rings/bracelets/necklaces?

**Comment by joshiejack** [comment]
Yes, working on that

**Comment by Adaptivity** [comment]
I can't fix some of missing names. Better you should do it. I'll make a list for you:
1) mariculture.upgrade.format (I don't know for what it needed)
2) mariculture.plans.redstone (should be maritech.plans.redstone)
3) mariculture.string.water (just water)
4) mariculture.FishingRod (Wooden fishing rod?)
5) mariculture.net.net (don't know)
6) mariculture.RodBlood (should be fixed in .lang file)
7) mariculture.sands.gas
8) All corals
9) mariculture.MobMagnet
10) mirrors/rings/bracelets/necklaces names

**Comment by joshiejack** [comment]
Thanks, I knew there was some I had missed when I messed with everything xD

**Comment by Adaptivity** [comment]
How to use rings/bracelets/necklaces formats? Provide an example if possible.
