### ISSUE TITLE
Crash on startup if Blood Magic not present

### ISSUE THREAD

**Issue by Adaptivity** [joshiejack/Mariculture#221]
Tested on the latest Forge, latest Mariculture Deluxe. Simply try to start the game without Blood Magic. Crash log: http://pastebin.com/9pq2QT8v
This is your first bugreport for new version :smile:

**Comment by Tsyklop** [comment]
me to crash!

**Comment by joshiejack** [comment]
I'll probably deal with this on Wednesday or something (Day after visitng my dads). Just working on other things atm, too much in the zone with it xD.

**Comment by Adaptivity** [comment]
It's ok joshie. We will wait.
