### ISSUE TITLE
[1.2.4b] Fish Feeder Broken

### ISSUE THREAD

**Issue by thephoenixlodge** [joshiejack/Mariculture#224]
The fish feeder seems rather broken. Fish food is not added to the tank, either by pumping it in, dropping fish meal in surrounding water, or by placing bottles of it in the gui. It also does not seem to be detecting cooling upgrades from what I can tell, as well as not detecting the water around it.
Image: http://i.imgur.com/bgF240i.png

**Comment by joshiejack** [comment]
Checking over this. The food will be related to the water. As the size of the tank depends on the amount of water. Working on it now.

**Comment by joshiejack** [comment]
Fixed in dev grab from ondraster.cz:8080/job/Mariculture/

I'll release properly soon, just waiting on something ^_^.
