### ISSUE TITLE
[1.2.4b] Crash With Blood Magic 1.3.0b

### ISSUE THREAD

**Issue by thephoenixlodge** [joshiejack/Mariculture#225]
No Idea what changed bewteen BM 1.3.0a and 1.3.0b to cause this, but with 1.3.0b installed, Mariculture causes a crash on launch with a NoClassDefFoundError
Crash report: http://pastebin.com/9d3Lc9z4

**Comment by joshiejack** [comment]
https://github.com/joshiejack/Mariculture/issues/223
