### ISSUE TITLE
Crash with blood magic 1.3.0b-3

### ISSUE THREAD

**Issue by SinusoidalC** [joshiejack/Mariculture#226]
As https://github.com/WayofTime/BloodMagic/issues/216 says, Mariculture's BM integration cause this crash.
I'm using Mariculture Deluxe-1.2.4b & BM 1.3.0b-3. Crash while stratup.

**Comment by TehNut** [comment]
There's already 2 closed issues for this. ( #225 and #223 ). 

It was also fixed in this commit: a3bb861603d7eb8e4c9828b6dc150bbde5a8b675
