### ISSUE TITLE
[1.2.4c-1]Auto-Fisher + more broken

### ISSUE THREAD

**Issue by thephoenixlodge** [joshiejack/Mariculture#228]
It was not broken in 1.2.4b, but the changes in this new build have resulted in it having no texture and causing a crash when right-clicked

Crash report: http://pastebin.com/xZ2DL7id

**Comment by joshiejack** [comment]
Odd. Will look in to it. I didn't touch anything to do with it :S

**Comment by thephoenixlodge** [comment]
Expanding on this, textures for a number of other items are broken too, namely the Neoprene, Scuba lens, Plastic, Yellow Plastic, Dragon spawn egg, life core and creative battery

**Comment by joshiejack** [comment]
To be honest. It sounds like you downloaded the Base instead of Deluxe.

**Comment by thephoenixlodge** [comment]
http://i.imgur.com/NY5knjj.png
Is there a chance that the base and deluxe were labelled wrong on the Jenkins? *Goes and tests*

**Comment by thephoenixlodge** [comment]
Ok, things seem to be really weird with this version, when I had it installed before testing if the base and deluxe versions were labelled correctly, the fish feeder was working fine, as it should have been. However, after subbing the base version in temporarily then going back to deluxe, it has suddenly decided that it will once again not detect the size of the tank. I've tried completely removing the mod and loading up the world to clear all Mariculture content before dropping it back in, but it still remains broken, not detecting the tank size, whether on an existing world or a new one. It is however correctly detecting the cooling upgrades, which it wasn't in 1.2.4b.
As to the autofisher, I've also realized that it, along with a couple of other things (namely the multiblock air compressor) aren't even showing up in NEI or in the creative menu.
I don't know whether its related to the way I have it set up in the pack, or whether the version is just a bit buggy.
Here's a zip containing the mariculture config files from the install, incase that's of any use, but honestly I'm just now sure what's going on: https://www.dropbox.com/s/clhgtnhfj1d0qpd/mariculture.zip?dl=0

**Comment by mattymaats** [comment]
Hi guys,

I'm using Mariculture-Deluxe-1.7.10-1.2.4b and the server keeps crashing with this crash report.

http://pastebin.com/KQyHn4Zr 

so I originally thought it was to do with mekanism reported under 

https://github.com/aidancbrady/Mekanism/issues/2097

Anyway so I've been going through all the mods checking who has which api when the server went down and I noticed this in the console.

http://pastebin.com/dDxELb8t

About half way down this shows up which makes me think it's the cofh api that's distributed within the mod?

[11:26:06] [Server thread/WARN] [/]:    at mariculture.core.gui.feature.FeatureRedstone$RedstoneMode.canWork(FeatureRedstone.java:42)
[11:26:06] [Server thread/WARN] [/]:    at maritech.tile.TileAutofisher.canWork(TileAutofisher.java:101)
[11:26:06] [Server thread/WARN] [/]:    at mariculture.core.tile.base.TileMachine.updateCanWork(TileMachine.java:142)
[11:26:06] [Server thread/WARN] [/]:    at maritech.tile.base.TileMachinePowered.receiveEnergy(TileMachinePowered.java:34)

**Comment by joshiejack** [comment]
@mattymaats please put that in a seperate issue.

@thephoenixlodge I'll do some digging.

**Comment by joshiejack** [comment]
I think I see the issue with the textures. In dev it's using the right textures. But on compiling it's trying to use the files from mariculture/textures instead of maritech/textures. I'll see what's going on.

**Comment by mattymaats** [comment]
As the server is for a public server I've had to try and put in a way that doesn't crash it.

Rolling back to mekanism .127 seems to resolve the issue but I'll show you one of the set-ups that caused the crashes.

http://prntscr.com/5vcdi3

Checking within EnderIO it contains part of the mekanism API which I tried updating to test, that didn't resolve the issue. EnderIO also contains some COFH api as well but they have the newest 1.7.10R1.0.3 version.

I'm not really very clued up on mods at this depth so just trying to help as much as possible xD Do you think this could have been what caused the issue?

I'll try the Dev version you've put up with all the other tech mods tomorrow night on one of our dev servers to see if it has resolved the issue. Thanks for getting back to me so quickly though :)

**Comment by joshiejack** [comment]
@thephoenixlodge build 4 should have fixed the problem please give it a go when you can :)

http://joshiejack.uk:8080/job/Mariculture/

**Comment by thephoenixlodge** [comment]
Got a crash with build 4 when hovering over the environment error tooltip in the fish feeder gui
http://pastebin.com/6SYM4wHY

**Comment by joshiejack** [comment]
sorry for all the issues... but thanks for helping

**Comment by thephoenixlodge** [comment]
No problem, Mariculture plays a big part in my pack (Regrowth) and I'm basically just play testing its features to be able to write quests about them so others can learn how to use it too

**Comment by joshiejack** [comment]
ok try 6

**Comment by thephoenixlodge** [comment]
Ok, all seems to be working correctly now. One question though, is the fish tank block (which I presume to be akin to the apiarists chest from forestry) supposed to be able to store 250*54 fish with just the one block?

**Comment by joshiejack** [comment]
Yeah. I had plans to make it better for 1.3. But scrapped when I decided to stop working on this version of Mariculture. So the suckiness of it stays :p

**Comment by thephoenixlodge** [comment]
Ok cool. I may just remove the recipe for it then - its a lot of storage for 1 block in a pack with limited storage options.
The only other thing I noticed was that the recipe images in all the books are very broken, mostly displaying some or none of the ingredients or outputs, but its not exactly a mechanic breaking issue so I'm not too concerned if you don't think its worth fixing.

**Comment by joshiejack** [comment]
Yeah I noticed that. It's just tedious work to fix it. And afterall it is just recipes, which you can look up in NEI anyways.
