### ISSUE TITLE
Mariculture-Deluxe-1.7.10-1.2.4b -> Outdated Cofh energy API?

### ISSUE THREAD

**Issue by mattymaats** [joshiejack/Mariculture#229]
Hi Josh,

As requested.

I'm using Mariculture-Deluxe-1.7.10-1.2.4b and the server keeps crashing with this crash report.

http://pastebin.com/KQyHn4Zr

so I originally thought it was to do with mekanism reported under

aidancbrady/Mekanism#2097

Anyway so I've been going through all the mods checking who has which api when the server went down and I noticed this in the console.

http://pastebin.com/dDxELb8t

About half way down this shows up which makes me think it's the cofh api that's distributed within the mod?

[11:26:06] [Server thread/WARN] [/]: at mariculture.core.gui.feature.FeatureRedstone$RedstoneMode.canWork(FeatureRedstone.java:42)
[11:26:06] [Server thread/WARN] [/]: at maritech.tile.TileAutofisher.canWork(TileAutofisher.java:101)
[11:26:06] [Server thread/WARN] [/]: at mariculture.core.tile.base.TileMachine.updateCanWork(TileMachine.java:142)
[11:26:06] [Server thread/WARN] [/]: at maritech.tile.base.TileMachinePowered.receiveEnergy(TileMachinePowered.java:34)

Don't mean to jump in here but thought it could be linked & it's the same block showing up in my issue.

FYI - Package-info for Cofh energy API distributed within mariculture - package

cofh.api.energy;
import cpw.mods.fml.common.API;
@API(apiVersion="1.7.10R1.0.0", owner="CoFHAPI", provides="CoFHAPI|energy")
abstract interface package-info {}

Package-info for Latest Cofh energy API

package cofh.api.energy;
import cpw.mods.fml.common.API;
@API(apiVersion="1.7.10R1.0.3", owner="CoFHAPI", provides="CoFHAPI|energy")
abstract interface package-info {}

**Comment by mattymaats** [comment]
This is a list of my mods just in case it helps - http://prntscr.com/5vbtcw

I'm just trying to roll mekanism back to Mekanism-1.7.10-7.1.1.127 to see if that helps.

**Comment by joshiejack** [comment]
Can you test it with build 3. I updated the API.

http://joshiejack.uk:8080/job/Mariculture/

**Comment by mattymaats** [comment]
As the server is for a public server I've had to try and put in a way that doesn't crash it.

Rolling back to mekanism .127 seems to resolve the issue but I'll show you one of the set-ups that caused the crashes.

http://prntscr.com/5vcdi3

Checking within EnderIO it contains part of the mekanism API which I tried updating to test, that didn't resolve the issue. EnderIO also contains some COFH api as well but they have the newest 1.7.10R1.0.3 version.

I'm not really very clued up on mods at this depth so just trying to help as much as possible xD Do you think this could have been what caused the issue?

I'll try the Dev version you've put up with all the other tech mods tomorrow night on one of our dev servers to see if it has resolved the issue. Thanks for getting back to me so quickly though :)
