### ISSUE TITLE
Reading the guide book will cause "Force Unicode: On" failed.

### ISSUE THREAD

**Issue by oldjunyi** [joshiejack/Mariculture#230]
Before I open the book:
![a](https://cloud.githubusercontent.com/assets/641817/5857759/17b6026e-a289-11e4-9765-6948cab9ce1d.png)

Then:
![b](https://cloud.githubusercontent.com/assets/641817/5857936/6a081c9a-a28a-11e4-9952-19de287f30ad.png)

After I close the book, everything remains in "Unicode-Off" state:
![c](https://cloud.githubusercontent.com/assets/641817/5858137/f1240850-a28b-11e4-8252-b6f5af3f74d5.png)

In some Unicode language like Chinese, Japanese, the guide book will turns ASCII characters into "Unicode-Off" but leave other characters unaffected, which makes the game GUI looks quite messy.

**Comment by joshiejack** [comment]
This should have been reported on the Enchiridion github. Not sure it will be fixed though, since I am working on Enchiridion 2 anyways.
