### ISSUE TITLE
Mariculture and Bloodmagic Comparability 

### ISSUE THREAD

**Issue by Insanity897** [joshiejack/Mariculture#231]
at the moment with the blood magic plugin turned on you get this error 
There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: WayofTime/alchemicalWizardry/common/items/BoundArmour

luckily you can avoid it by turning the plugin off Good Feature by the way

**Comment by joshiejack** [comment]
https://github.com/joshiejack/Mariculture/issues/226 https://github.com/joshiejack/Mariculture/issues/225 https://github.com/joshiejack/Mariculture/issues/223
