### ISSUE TITLE
Fish appearing as Minecraft ones.

### ISSUE THREAD

**Issue by nightandstars** [joshiejack/Mariculture#233]
I've been playing Regrowth recently and some of the fish appear as Minecraft ones, making it impossible to know the sex and stuff like that.
![2015-01-24_10 28 59](https://cloud.githubusercontent.com/assets/10685913/5887938/6e8ba186-a3b8-11e4-89b9-1a0f5e47b34d.png)

**Comment by joshiejack** [comment]
Those fish are dead.

**Comment by nightandstars** [comment]
Oh ok thank you a lot!
