### ISSUE TITLE
Scuba tank cannot be filled

### ISSUE THREAD

**Issue by BionicFelps** [joshiejack/Mariculture#234]
The scuba tank can't be filled from a compressor, powering it with mekanism universal cable hooked to an energy cell, right click on it with an empty scuba tank, still have empty scuba tank. (the green bar is full).  My setup includes a number of mods, but this doesn't seem like something that's susceptible to a mod interaction problem...  In the meantime, I'm going to minetweak in a crafting recipe involving a filled oxygen tank from mekanism >.>

edit --
It's only green because I hacked the textures into both folders, but you already know about that bug, couldn't find an example of the scuba one... And also Awsome scuba gear, Mekanism's is useless... It actually actively dispells night vision (and all other effects) while active, removing my ability to see anything at all underwater... whereas this one smartly clears the underwater fog and slightly brightens even without night vision/doesn't dispel my night vision...

**Comment by BionicFelps** [comment]
Finding more bugs, but they're to do with portions of the mod that are going to disappear in 2.0 >.>

Can't wait btw, the mod looks like it was pretty awesome before it started dabbling in tech :P

**Comment by joshiejack** [comment]
Still want to fix all those I can in 1.7.10 :p

**Comment by BionicFelps** [comment]
Well, not sure I could repeat this one... On a server, put a vat down, and some lava in it, shortly after got forcibly disconnected, couldn't reconnect until the mod was disabled (thus deleting the vat)

**Comment by joshiejack** [comment]
Was there anything of note in any of the logs?

**Comment by BionicFelps** [comment]
http://pastebin.com/sptiPbwP

(Cooksters is me)

It didn't seem to have any record of my attempts to rejoin, I just got "server refused connection" or something similar, it could very well be because of all the mods I'm running

**Comment by BionicFelps** [comment]
Ok, tracked down the disconnection, it wasn't Mariculture's fault... It's an issue with Forge 1230 (and possibly some other versions) that certain mods could trigger...

http://bevolj.com/forums/index.php?threads/netty-error-research.106/

The reason I didn't see anything odd in the logs was that it was in the client side logs...

**Comment by BionicFelps** [comment]
Don't forget the scuba tank thing! (sorry, my bad to put em on the same one)

**Comment by joshiejack** [comment]
No worries xD.

**Comment by joshiejack** [comment]
Sorry that I haven't gotten around to fixing this one yet. It involves more digging than other fixes and I'm just having too much fun working on other things. :p

**Comment by BionicFelps** [comment]
No worries, I make bug reports more for the mod authors than myself!

**Comment by Dreghert** [comment]
Hey, joshiejack. First, gotta say, loving the mod.

But... I am having this issue as well, and on a server (Serendipity, using the Unlimited mod pack) where I cant go in and add recipes to get around it. If a solution could be found, I would be very happy. I did put in a request to the mods of the server to see if they could add a recipe to make it work, so maybe they will, but an update to the mod would be easier to get them to implement.

**Comment by Dreghert** [comment]
um... what? I've tried a simple right click, tried right clicking and holding, tried all manner of right clicky....ness. nothing has worked for me.

**Comment by joshiejack** [comment]
It's not going to work unless you update the mod :P

**Comment by Dreghert** [comment]
oh. um. i knew that. honestly. XD

on a new server, which has the new version apparently. just tried it. thanks for your awesome work, btw!
