### ISSUE TITLE
Random crash when looking up recipes in NEI, references the Casting Handler

### ISSUE THREAD

**Issue by thephoenixlodge** [joshiejack/Mariculture#236]
This crash is popping up rather frequently and randomly when looking up recipes in NEI, including for items completely unrelated to any Mariculture processing.
http://pastebin.com/g7Zygyru

While it references the NEI Casting handler from Mariculture, it seems to occur even if said handler is disabled in the configs so I'm a little stumped on trying to avoid it.

**Comment by thephoenixlodge** [comment]
Not quite so fixed. Got this crash with build 9: http://pastebin.com/ngcw16Jn
Looks like its now having a similar issue with the crucible furnace handler on looking up usage recipes.
Again its on completely unrelated items (this time was by right clicking a quest book)

**Comment by joshiejack** [comment]
God knows how my recipes are becoming null. Shouldn't happen under normal circumstances. Maybe modtweaked recipes I guess?

**Comment by thephoenixlodge** [comment]
I am using modtweaker to change a few casting and crucible recipes.
This file should be the one with most of these recipes/removals, but there might a couple of others in the other files in that folder: https://github.com/thephoenixlodge/Regrowth-Stuff/blob/master/scripts/earlytech.zs
It does seem to not like me using the /mt reload command anymore either, usually telling me a modification is stuck, so I have to reboot the game completely.

**Comment by joshiejack** [comment]
I don't mind adding the checks but yeah that's what will be causing the crashes >.<

**Comment by thephoenixlodge** [comment]
Ok, thanks for this.

**Comment by joshiejack** [comment]
I just want as many of these crashes/issues sorted... So I don't have to keep fixing them :dancer:

**Comment by thephoenixlodge** [comment]
This is still popping up randomly when looking up the recipe for an item with build 10, though far far less frequently than before: http://pastebin.com/HMk4zEBM

**Comment by joshiejack** [comment]
Different recipe handler :P

Previous was crucible, this is casting. *Fixes*
