### ISSUE TITLE
No natural gas

### ISSUE THREAD

**Issue by BionicFelps** [joshiejack/Mariculture#237]
Can't seem to locate any natural gas... Factory is currently disabled (cause of crash bug and general glitchiness that's probably being worked on), disabled railcraft as well because I was suspicious that those abyssal sphere thingies were taking it over, no dice.  As much as I know miners love to find pockets of invisble debuffing gas, it's probably better that way >.>

Sorry about the random bug spam too, just testing various features!

**Comment by joshiejack** [comment]
Natural Gas is only generated when factory is enabled. It has no use outside of the factory module.
