### ISSUE TITLE
Recipe Conflict with Refined Relocation

### ISSUE THREAD

**Issue by Neodark7** [joshiejack/Mariculture#243]
Hey there is an recipe conflict between your two mods, relocator and iron construction block, i report it on both. :) https://github.com/Dynious/RefinedRelocation/issues/272

![sans titre-1](https://cloud.githubusercontent.com/assets/7981869/6198370/ef6111b6-b3fc-11e4-85ca-0eba610696af.png)

**Comment by joshiejack** [comment]
use minetweaker or other similar mods

**Comment by Neodark7** [comment]
already done but... if any of you can fix it in his mod it would be better :/ like that 
![image](https://cloud.githubusercontent.com/assets/7981869/6198474/2f42baf8-b404-11e4-8215-b422fceeb63f.png)

**Comment by joshiejack** [comment]
im not changing it, it would be a pita to change every recipe conflict that comes up, this is not the first. it's what minetweaker is for.

**Comment by Neodark7** [comment]
well... and no i have ic2 and it's work fine.
