### ISSUE TITLE
Crash when generating the nether

### ISSUE THREAD

**Issue by demethan** [joshiejack/Mariculture#256]
Hi, 

I tried multiple version of 1.2.4a-f

here is the crash log.

1.7.10-1.2.4f http://pastebin.com/aN5y8X3T

Thanks

*edit

tried with Forge 1291 and 1307

Mods included in the pack 
http://www.atlauncher.com/pack/DelusionsofAdequacy

Thanks again.

**Comment by joshiejack** [comment]
https://github.com/joshiejack/Mariculture/issues/255

**Comment by demethan** [comment]
Here is a pastebin of my config 

http://pastebin.com/MzTJL5GY

the nether is blacklisted. 

the crash only happens on a fresh nether gen.  If the nether was generated before, it loads fine. 

thanks again.

**Comment by joshiejack** [comment]
New nethers generate fine for me, the code is not called if it is blacklisted. Some other mod is breaking it. Please test on it's own/when it breaks.

**Comment by demethan** [comment]
hrm.  I think I know the mod you speak off. I think Gregtech might have something to do with it.

I will test further tomorrow. 

For  the server , I'll pre-gen the nether without Mariculture in the pack.  Then put Mariculture back in. 

Thanks for your help.

**Comment by demethan** [comment]
Hi, Gregtech does something to your blacklist. If  I can't find a work around, I'm sorry to say I will have to remove Mariculture from my pack. 

Would you have any other suggestion that could help to fix this. 

Thanks.

**Comment by joshiejack** [comment]
Remove it then. There's nothing I can do.

**Comment by demethan** [comment]
Sad to hear.
Is there is no way to replace the blacklist for a whitelist in future builds?
It would be simpler config wise to whitelist the dimessions you want Mariculture to gen in.

Please consider it.  I Thank you for your dedication.

**Comment by joshiejack** [comment]
in this instance it would make no difference since it is bypassing the checks.

Actually, I had a look a look at my code and forgot that you can stop it registering the replace blocks. (No limestone/rutile generation though). But with gregtech the latter doesn't matter, and you probably have chisel or something for limestone.

Change: Biome Top Block Replacements > Enable to false and it won't register the event/gen those. So it won't crash.

**Comment by demethan** [comment]
That worked beautifully.  Mariculture stays.

Thanks.
