### ISSUE TITLE
Drowning Issue

### ISSUE THREAD

**Issue by devryb** [joshiejack/Mariculture#257]
Is there a way to disable the Hardcore Diving mode in this mod?
It appears theres a compatibility issue somewhere with it and one of the other mods/plugins we use.
Players don't take any damage at all when their air runs out.

I have set this to 0, however it's still an issue so I'm wonder if there's another config option we are missing for it or some way that we can get this feature disabled entirely in the mod somehow
    I:"Hardcore Diving Setting"=0

**Comment by joshiejack** [comment]
It does not activate unless that setting is greater than 0.

**Comment by devryb** [comment]
Somehow updating World Edit to version 6 fixes this...
Sorry for the bother :)
