### ISSUE TITLE
Lag issue with set fire

### ISSUE THREAD

**Issue by devryb** [joshiejack/Mariculture#261]
Hi, we have come across an imcomptibility with a plugin and were hoping you could point us in the right direction with this on how we can maybe get it fixed.

http://puu.sh/gxPvJ/05d72afed7.png

**Comment by joshiejack** [comment]
Does the plugin stop fire spread or something? Best I can offer is to add a config to disable gas from trying to catch on fire.

**Comment by devryb** [comment]
Ok I had a hunch that's what it was, we appreciate the config option as well.
The plugin is a land claim system that also protects against fire spreading so that's most likely what it is.

**Comment by devryb** [comment]
Confirmed this fixes it
