### ISSUE TITLE
TiC Fishing Rods?

### ISSUE THREAD

**Issue by InkDragon** [joshiejack/Mariculture#264]
As far as I know Boni doesn't have any current plans to implement them, however all the artwork is done for them. I really only see them as possibly being useful with mariculture so I was wondering if there was any chance you could integrate them as part of the mod like the titanium parts?

**Comment by joshiejack** [comment]
Not likely. Tinkers has broken my mod so many times, I don't really wanna work on something else to do with tinkers.

**Comment by Yulife** [comment]
Lazy joshie!
