### ISSUE TITLE
[BUG] Not auto installing Enchiridion!

### ISSUE THREAD

**Issue by dylanpiera** [joshiejack/Mariculture#265]
I've made a custom block in Quadrum and gave it recipes with Minetweaker.
When trying to check the recipe in game with NEI it crashes with this crash report:
http://pastebin.com/RtZ8BuSg

Then i removed mariculture and it didn't crash anymore?
Am i doing something wrong or is this just a compatibility issue?
(For the record: When the block has no recipe it also crashes!)

**Comment by dylanpiera** [comment]
Extra: I've tested this with any recipe. Still ain't working!

**Comment by dylanpiera** [comment]
Problem is solved!
Installed Enchiridion fixed everything. All mariculture item showed up and nei shows the recipes now

Il chance this to bug report for not auto installing enchiridion. Cause it did in the old versions

**Comment by joshiejack** [comment]
You have a mod that breaks the auto installer. Imma update it 4o kihiras new version next update.

**Comment by dylanpiera** [comment]
You mean the mariculture version or is another mod blocking it?

**Comment by joshiejack** [comment]
No another mod, the current system overrides the main menu. The new way works differently.
