### ISSUE TITLE
Incompatibility with Forge Essentials

### ISSUE THREAD

**Issue by LightningLdr180** [joshiejack/Mariculture#266]
I was having an issue with the newer versions of Forge Essentials crashing with:
java.lang.RuntimeException: java.lang.ClassNotFoundException: cpw.mods.fml.common.asm.FMLSanityChecker

After testing it on a clean server and re-adding mods one-by-one, this problem only occurs when Mariculture is present.  Each mod loads just fine without the other one.  I wanted to reach out here and see if maybe you had an idea of what the issue might be.  

Here is my log for the error:
http://pastebin.com/Bkne2FBf

And here is the issue report on the Forge Essentials github:
https://github.com/ForgeEssentials/ForgeEssentialsMain/issues/1333

Thanks for your time!

**Comment by luacs1998** [comment]
For the record, FE is using transformers supplied by the [Mixin](https://github.com/SpongePowered/Mixin) project, which will be used by the Sponge API in the future.

**Comment by simon816** [comment]
To save a bit of time, this line - [VanillaOverride:108](https://github.com/joshiejack/Mariculture/blob/1.7.10-1.2.4/src/main/java/mariculture/fishery/VanillaOverride.java#L108) probably has something to do  with it.

**Comment by joshiejack** [comment]
Considering it's been like that since my first 1.7 updates and it's had no issues with any other mods. I've got no clue what I'm supposed to do here.

**Comment by olee** [comment]
Looking at the [code](https://github.com/joshiejack/Mariculture/blob/1.7.10-1.2.4/src/main/java/mariculture/fishery/VanillaOverride.java#L108) I have to agree, that is not really written nicely...
We would appreciate it, if you could take a look at the patching process and see where this problem comes from.
We will try to find the root of the problem, too.

**Comment by Adaptivity** [comment]
@joshiejack fixed in Forge 1399. Go close it.
