### ISSUE TITLE
forge fluid registry issue? 

### ISSUE THREAD

**Issue by odenthefish** [joshiejack/Mariculture#269]
i keep getting this crash on my 1.7.10 modpack http://pastebin.com/vnnHFtV5 i am using the latest mariculture disabling all modules and plugins does not help 
probably i am doing something wrong but i can not find it

**Comment by joshiejack** [comment]
Forge 1355+ broke fluids.

**Comment by odenthefish** [comment]
oh i heard nothing of that very strange to do that...
 thank you for the quick reply! i was stumped on what was broken

**Comment by DrummerMC** [comment]
some mods dosn't corectrly register the fluids in the new fluid registry. Your mod is one of them. I try to fix this for you

**Comment by DrummerMC** [comment]
Hopefully fixed in #271.
