### ISSUE TITLE
Something is wrong with plugins

### ISSUE THREAD

**Issue by lokster666** [joshiejack/Mariculture#272]
15.04 10:21:40 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
15.04 10:21:40 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.reflect.Method.invoke(Method.java:606)
15.04 10:21:40 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
15.04 10:21:40 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
15.04 10:21:40 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
15.04 10:21:40 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at mariculture.Mariculture.init(Mariculture.java:58)
15.04 10:21:40 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at mariculture.plugins.Plugins.init(Plugins.java:105)
15.04 10:21:40 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at mariculture.plugins.Plugins$Plugin.load(Plugins.java:34)
15.04 10:21:40 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at mariculture.plugins.PluginForestry.init(PluginForestry.java:79)
15.04 10:21:40 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.NullPointerException
15.04 10:21:40 [Server] Server thread/WARN [Mariculture]: Something went wrong with Forestry Plugin at INIT Phase
15.04 10:21:40 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
15.04 10:21:40 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
15.04 10:21:40 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:210)
15.04 10:21:40 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:319)
15.04 10:21:40 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97)
15.04 10:21:40 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:691)
15.04 10:21:40 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
15.04 10:21:40 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
15.04 10:21:40 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
15.04 10:21:40 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
15.04 10:21:40 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
15.04 10:21:40 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
15.04 10:21:40 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.reflect.Method.invoke(Method.java:606)
15.04 10:21:40 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
15.04 10:21:40 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
15.04 10:21:40 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
15.04 10:21:40 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
15.04 10:21:40 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
15.04 10:21:40 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
15.04 10:21:40 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
15.04 10:21:40 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
15.04 10:21:40 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
15.04 10:21:40 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
15.04 10:21:40 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.reflect.Method.invoke(Method.java:606)
15.04 10:21:40 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
15.04 10:21:40 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
15.04 10:21:40 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
15.04 10:21:40 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.reflect.Method.invoke(Method.java:606)
15.04 10:21:40 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
15.04 10:21:40 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
15.04 10:21:40 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
15.04 10:21:40 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at mariculture.Mariculture.init(Mariculture.java:58)
15.04 10:21:40 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at mariculture.plugins.Plugins.init(Plugins.java:105)
15.04 10:21:40 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at mariculture.plugins.Plugins$Plugin.load(Plugins.java:34)
15.04 10:21:40 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at mariculture.plugins.PluginTConstruct.init(PluginTConstruct.java:70)
15.04 10:21:40 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at mariculture.core.util.Fluids.getFluidName(Fluids.java:59)
15.04 10:21:40 [Server] Server thread/INFO [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.NullPointerException
15.04 10:21:40 [Server] Server thread/WARN [Mariculture]: Something went wrong with TConstruct Plugin at INIT Phase

**Comment by joshiejack** [comment]
https://github.com/joshiejack/Mariculture/issues/268
