### ISSUE TITLE
Not accepting RF!

### ISSUE THREAD

**Issue by BionicFelps** [joshiejack/Mariculture#273]
Thermal expansion is not installed, but there are other mods that produce and consume RF, COFH core is installed, and the Mariculture machines seem to refuse to operate on any method of delivering RF (rotarycraft dynamo, pneumaticcraft dynamo, AE2 RF tunnel, electrical age ->other converter block.

I was going to test with thermal expansion installed, but can't get it at the moment due to the download site not loading for me.

**Comment by joshiejack** [comment]
Works for me..

**Comment by BionicFelps** [comment]
I can't muss with it right now, but I'll try to figure out what's going on over the weekend...

**Comment by BionicFelps** [comment]
I've gotten around to testing it, the pack is currently using version 1.2.4.1a of Mariculture which is a version behind I believe...  I'll be making an update soon.  But I was wrong about pneumaticcraft, that dynamo seems to work (although I removed the CoFH folder from Mariculture to ensure all the mods were using the same version of the API.) the RotaryCraft dynamo, and the electrical age converter both don't work.  The thermal expansion (which isn't in the pack, but I threw it in for testing) creative energy cell works fine as well.

All of these items work perfectly well with RF consuming blocks from other mods, so I'm not sure if it's like a push/pull problem (mariculture expecting RF to be pushed, and the other mods expecting it to be pulled).  In the update I'm making I intend to add EnderIO as well as update all mods to their latest versions, so I'll do that now and report back (might be a bit, I have to update documentation while I do this).

**Comment by joshiejack** [comment]
The mods you tried providing power are outdated with the rf api, they're only providing power to IEnergyHandlers (old rf). My machines are IEnergyReceiver

**Comment by BionicFelps** [comment]
aha, thanks; Hopefully this will be taken care of when I update them... They all have updates waiting... If not I'll put this in their respective issues areas.
