### ISSUE TITLE
(Request) Enchantments

### ISSUE THREAD

**Issue by sonicbrandyn** [joshiejack/Mariculture#276]
(I didnt know where to put this)
Could i suggest an option to disable some enchantments in mariculture with the configs?
I love mariculture but i hate the enchantments like, sonic the hedgehog and flight
You might just say: "Just dont use those enchants"
but i want my modpack to be a public server and i dont want any way to fly in my modpack ect

**Comment by joshiejack** [comment]
Set their ids to 0. That will disable them.
