### ISSUE TITLE
[SUGGESTION] WAILA integration for oysters

### ISSUE THREAD

**Issue by Nova001Sol** [joshiejack/Mariculture#277]
Look, I really don't need anything fancy, I just want WAILA to tell me if my oysters have produced a pearl or not. This is partly because yellow pearls and sand look almost the same to me, and partly because I have a colorblind friend that doesn't see the differences at all. Ideally, I'd also like to see WAILA tell me if the oyster has sand in it, so if it is empty/working/done.

**Comment by joshiejack** [comment]
Sand is actually meant to be smaller to make it easier to tell. That's a bug in the currently released version.

**Comment by joshiejack** [comment]
Sand is smaller again in 1.3.0 so will close this
