### ISSUE TITLE
More localization

### ISSUE THREAD

**Issue by Adaptivity** [joshiejack/Mariculture#280]
@joshiejack since you actively working on 1.7.10 version I'm requesting moar localization support! :smile: 
1) *mariculture.water* string should have %s tag for swapping word with amount.
2) I need to individually translate EACH ring/bracelet/necklace/bucket hat. So, there will be million strings with differently colored pearls for each item (only in ru_RU.lang of course)
3) I need to individually translate each *Dried* variant of coral and kelp.
This finally makes my translation as perfect as it possible.

**Comment by joshiejack** [comment]
Slavedriver!

**Comment by Adaptivity** [comment]
I just want translate all the stuff! :smile:

**Comment by Adaptivity** [comment]
And again I found [this block](http://i.imgur.com/QumZmkv.jpg) with broken localization.

**Comment by joshiejack** [comment]
That block doesn't exist. The metadata only goes up to 11. :P

**Comment by Adaptivity** [comment]
But why it in NEI? :D But meh.
