### ISSUE TITLE
A crash about using Mariculture-Deluxe-1.7.10-1.3.0-15......

### ISSUE THREAD

**Issue by UUUii** [joshiejack/Mariculture#289]
Oh...My heart is broken.T。T
https://gist.github.com/UUUii/9fd681a3fbaef0f3990a

**Comment by joshiejack** [comment]
1.3.0 needs the dev builds on ench 2.

**Comment by UUUii** [comment]
But when i using build 2,it will download build 1 automatic......:P

**Comment by joshiejack** [comment]
The autodownloader can't be updated until the ench2 update is officially out.

**Comment by UUUii** [comment]
OK,I try again,thanks for your answer:3

**Comment by UUUii** [comment]
And sorry about my poor English.
