### ISSUE TITLE
RailCraft Abyssal Stone (minor bug)

### ISSUE THREAD

**Issue by BionicFelps** [joshiejack/Mariculture#292]
The Abyssal Stone spheres spawn, and Mariculture's deeper oceans uncover them.  This is not really a problem...

But the spheres seem to spawn before limestone, hollow out their insides, but then get filled with limestone.  This is a very minor bug in my opinion.  Not sure if there's any easy fix... Minus specifically programming around abyssal stone, if my theory is right, it may be possible to simply get limestone earlier in the chunk gen, which it may already be, and Railcraft just doesn't remove anything but smooth stone... I'm not really certain how that works.  Whatever the case, without Mariculture, they're typically hollow, with it, they're filled with limestone.

**Comment by joshiejack** [comment]
They spawn after limestone. Limestone isn't replaceable because then you end up with horrible stone filled ores all throughout it. This is a non issue.
