### ISSUE TITLE
Some mistakes about fish's specialty's text.

### ISSUE THREAD

**Issue by UUUii** [joshiejack/Mariculture#294]
Hi joshiejack,I find some mistakes when I'm working in localization,likes:
1.mariculture.book.fish.cod=Gives leather when melted down.....but it doesn’t the leather,it's bone.....
2.On the book,stingray's specialty's text is Blinds and confuses entities.

**Comment by UUUii** [comment]
And sorry about my poor english:D

**Comment by UUUii** [comment]
Sorry about my poor english againT-T

**Comment by joshiejack** [comment]
#1 I accidentally removed that
#2 what?

mariculture.book.fish.stingray=Poisons entities in  their water territory.

Also half the new fish stuff isn't implemented yet.

**Comment by UUUii** [comment]
2.On the book,stingray's specialty's text is Blinds and confuses entities.......It's meaning that the text doesn't display in the right place,when i open the page of stingray i just seeing that  Blinds and confuses entities.
And also I have a question that am I pulling request the file call 'mariculture_fish_breeding_zh_CN.json' which turn down the size of 'MIN ROD'?

**Comment by joshiejack** [comment]
I wouldn't bother translating things yet. That book is actually going to change. As well as rewriting some others. And did you use the jenkins build or compile yourself for the sting ray thing? It says the right thing for me. There was bug where it said the wrong thing, but I fixed that, but didn't make a new build..

**Comment by UUUii** [comment]
OK,I see,so I just need to wait for the new build:D
So......I will be late to pull request the zh_CN.lang though it was finished.
