### ISSUE TITLE
Feature request: WOOD (and other junk from fishing nets)

### ISSUE THREAD

**Issue by BionicFelps** [joshiejack/Mariculture#296]
I'm living entirely underwater in my server... Wood is a problem >.> I have to go to land, or make myself a tree farm underground, both taxing propositions... I have plenty of string from fending off cave spiders, but no sticks...

So what I suggest is two fold, 
1) some underwater plant that produces something that would be in the ore dictionary as sticks (or just sticks themselves), it should be farmable... Probably something like reeds, but entirely underwater.
2) That first request is so you can make a fishing net, the second request is for the fishing net to have a chance at producing driftwood! This is just a type of log that the fishnet will drop as an entity just like it does fish...

Apologies if it already does (I haven't made one yet...)
The point here is that these suggestions fit in an underwater setting, and aren't something ridiculous like underwater trees... And work within existing mechanics to create a more complete experience out of the box! Of course, if the driftwood makes fish less likely to drop from the net it would reduce the current utility of it, so there's some kind of balance to be struck here...Of course this could go with other junk items and fishing tropes such as an old boot = leather in crafting grid, tire = rubber for the couple recipes that need it in Mariculture when a mod that has rubber is installed.  soggy leaves, smelt = leaf block...  All things that are harder to get from my undersea lair, and are useful in various ways.  (I need leaf blocks or other plant material typically harvested with shears to make ethanol in RotaryCraft). Fish breeding can be used for some of these things I believe... But you need wood to make a sifter to get started with that too :p

**Comment by joshiejack** [comment]
Probably won't happen. Maybe in 2.0 but not now. Not looking to add anything, just finalising what I have.
