### ISSUE TITLE
A question about the alive Silver-Stripe Blaasop.

### ISSUE THREAD

**Issue by UUUii** [joshiejack/Mariculture#297]
Hei joshiejack,my partner and I have a question about the fish called Blaasop.According to "FishBlaasop.java",I can catch a alive Blaasop when I was fishing in a place which its Temperature is 8°C and its Salinity is saline.However,I only find the alive cod and the alive goldfish no matter how long the past.Is that my own mistakes?XD

**Comment by joshiejack** [comment]
Which version?

**Comment by UUUii** [comment]
Yeah,the Mariculture-Deluxe-1.7.10-1.3.0-18.

**Comment by joshiejack** [comment]
Are you fishing below y32?

https://github.com/joshiejack/Mariculture/blob/1.7.10-1.3.0/src/main/java/mariculture/fishery/fish/FishBlaasop.java#L110

**Comment by UUUii** [comment]
none,at y60.

**Comment by UUUii** [comment]
I know that it will get the raw fish if fishing below y32.

**Comment by joshiejack** [comment]
Well they only appear below 32

**Comment by joshiejack** [comment]
No the catch chance is the chance to catch the fish at all. Which for the blaasop is 0% at anything y32 above, or 40% chance below y32.

And then the catch alive chance, is the chance that if you catch it, it will be alive. Which for the blaasop is a 75% chance.

**Comment by UUUii** [comment]
Oh...OK,I got it...But I'm only find the raw blaasop while  below 32.....i have caught much many raw blassop.

**Comment by UUUii** [comment]
Yeah...have caught a lot of raw blassop...however none appear a alive blasso.
