### ISSUE TITLE
CrossMod Problem with chunk generation

### ISSUE THREAD

**Issue by BakermanLP** [joshiejack/Mariculture#298]
Hello there,
I've got a problem with Mariculture and Fun World Generation. OK, water is a relativ rare thing here, but why not. 

The following error was caused, while creating a completly new world.

Here is the complete client log: http://paste.ee/p/Y6OFl
All other information about that modpack can be found here: https://github.com/BakermanLP/ProjectPhoenix

Can you fix that?

**Comment by joshiejack** [comment]
Change B:"Biome Top Block Replacements > Enable" to false in the mariculture worldgen config.
