### ISSUE TITLE
A question about the RF portion of this mod.

### ISSUE THREAD

**Issue by MtnDrew** [joshiejack/Mariculture#299]
So I'm playing a random assortment of mods I put together, mostly magic mods, and this mod plus forestry are the only ones that use RF. I've been reading through the Factory book and I haven't found any way to transfer RF with this mod by itself. So did I miss something, or do I need another mod to be able to transfer energy from the generators and charge the various machines and tools?

**Comment by joshiejack** [comment]
If you look at the sawmill page. There is a plan for custom rf blocks. These blocks transfer power. (If you have another option, that would be better though). But the mod does have a native way to move power around.
