### ISSUE TITLE
[Bug Report]Unable to get natural gas.

### ISSUE THREAD

**Issue by ProgrammedSoul** [joshiejack/Mariculture#301]
Running Mariculture 1.2.4.2 in minecraft 1.7.10. Found a bubbled block, dig down, find the room that cause slowness and other debuf, then put down air pump. The animation of air pump appeared but there is no output. Tried mariculture tank, openBlock tank, extraUtil drum, fluid transfer node, as long as moving the pump around, does not seems to work. BTW put down a torch does work...in another way.

My mod list:
ArgiCraft
AOBD AE
BibiloCraft
Bamboo
BC
Carpenter's block
Chisel2
ChiselFacades
ChiselTones
CodeChickenCore
Enchirdion
EnderZoo
EnhancedInventoies
ExtraBiomeXL
ExtraUtilities
fastcraft
forestry
GardenStuff
OptiFine
ProjectRed
StorageDrawers
TConstruct
Waila
YaGamoChattels
Ztones

I appreciate your great work on the mod and hope you may have some time to get around this bug, as a number of players in my server are blaming me for natural gas issue blocked mariculture tech tree.

**Comment by ProgrammedSoul** [comment]
BTW I forgot mentioned that I do right clicked the air pump...I also tried exteaUtil generator to power it with RF. In this case the RF is consumed but there are no animation, nor the output. Thank god the generator does not cause fire through.....

**Comment by joshiejack** [comment]
In 1.2.4.2 the air pump needs a redstone signal

**Comment by ProgrammedSoul** [comment]
Well I think I heard (mostly from a YouTube video)that redstone may light up nathral gas...
But anyway thank you I will go for a try!

**Comment by joshiejack** [comment]
Nah the redstone torch should be fine, either would you can always use a lever.
