### ISSUE TITLE
A question about the fish products.

### ISSUE THREAD

**Issue by UUUii** [joshiejack/Mariculture#304]
Hello joshiejack, my partner asked me that he met some problems when producting fish. As you konw, Netherfish mates with Neon Tetraeon will have 25 percent to product angler fish, but netherfish couldn't work with Neon Tetra together. For example, I build a tank where Netherfish can work normally, but when I was putting Neon Tetra into feeder, Netherfish showed "tank too small!!! +55 Lave" though lava was all around the feeder. Also I don't konw how to provide a suitable environment to Neon Tetra, half water, half of lava?
![fmu z g8 i6o1qsaq8a6r](https://cloud.githubusercontent.com/assets/11549990/8149650/e144f65a-12fd-11e5-8810-e540a56ee68e.jpg)
![tmd sws5zj rj8tf6yx t s](https://cloud.githubusercontent.com/assets/11549990/8149651/e2e02016-12fd-11e5-93a8-0a1b2a54c497.jpg)

**Comment by joshiejack** [comment]
Neon Tetra are SUPPOSED to be happy in lava. Seems like they aren't, must have slipped past >.>.

**Comment by UUUii** [comment]
Thank you so much:3

**Comment by UUUii** [comment]
Sorry about that, I had find some errors again. 
1. The fish breeding between Rainbow fish and Golwfish, Golwfish need lava or custard, Rainbow fish need water;
2. The fish breeding between Clownfish and Blazefish, Blazefish need lava or custard, Clownfish need water.
Yeah, It was demystified by the error about Netherfish XD.

**Comment by joshiejack** [comment]
It's interesting, I have those accepted water types in my breeding chart, I guess I just forgot to add them in to the code!

**Comment by joshiejack** [comment]
Ok that should get the last few: https://github.com/joshiejack/Mariculture/commit/149a0eab703c03c50a712e08dd4c7d7cae8fa6ae

**Comment by UUUii** [comment]
thx again:3
