### ISSUE TITLE
  Fluid registry issue with Mariculture and TSteelworks: Value Already Present: limestone.molten

### ISSUE THREAD

**Issue by belathus** [joshiejack/Mariculture#307]
http://pastebin.com/RU6GBDia

It was not a crash. And interestingly, with both mods installed, I can easily start the server or start a single player world. I cannot, however, join a server. Removing TSteelworks does fix this issue, but I'd rather not if I can help it.

I also submitted this to Ephys [here](https://github.com/Ephys/TinkersSteelworks/issues/106).

**Comment by Yulife** [comment]
This might sound silly but test it without CustomItems mod. I used to fiddle around with Limestone in that mod in the pack you get this from.

**Comment by joshiejack** [comment]
My molten limestone is registered as quicklime. So this has nothing to do with me. What forge version are you using btw.

**Comment by belathus** [comment]
Forge 1448. I've heard that this particular issue may be related to a change to Forge in 1407?

**Comment by TBK0000** [comment]
Forge 1421 changed fluids, I have submitted a pull request for the 1.3.0 and 1.2.4 branches for fix the issue and make Mariculture work with forge-1.7.10-10.13.4.1490-1.7.10.
