### ISSUE TITLE
Crash help

### ISSUE THREAD

**Issue by LiteraryRecluse** [joshiejack/Mariculture#308]
I was playing another mod and I crashed, and now I can no longer open that save file without the game crashing every time.  I posted the crash report on the mod's GitHub page, but since Mariculture is mentioned in the crash report I thought I'd post it here in hopes you could help me out as well.

Here is the report: http://pastebin.com/tNnRh4qe

It happened when I entered a portal to a different dimension in the other mod, now I'm either stuck in the portal or in the other dimension with endless/permanent crashes upon loading.

**Comment by joshiejack** [comment]
Add the dimension to mariculture's worldgen blacklist in the configs

**Comment by LiteraryRecluse** [comment]
Ah, awesome, I'm glad there is a fix!  But where is this blacklist at?  I have the world-generation.cfg file open (assuming that's what you mean) but I don't see any blacklist to add the dimension to.  The only thing I see is something under the Aquatic Generation section

 I:"Ocean Generation > Blacklisted Dimension IDs" <
        -1
        1
     >

So, how do I add it to the blacklist?  The Id is: 
I:"Ancient Treasure Room ID:"=-34
but I have no idea where to add it to the config.  I tried simply typing -34 in the brackets but it didn't work.

**Comment by LiteraryRecluse** [comment]
Should it look like this?

I:"Ocean Generation > Blacklisted Dimension IDs" <
-34
-1
1
>

If so, it's not working.  I've edited the file as such and created a new world and it still crashed.  Am I doing this wrong?

**Comment by joshiejack** [comment]
That should work. If it's not, then you must have the dimension id wrong. If you have another way to obtain limestone/titanium you can also disable it entirely by disabling the biome replace top blocks config. (or whatever it's called).

**Comment by LiteraryRecluse** [comment]
The replace top blocks option worked.  I'm going to turn it back on after I exit the dimension and hope it doesn't cause too many problems.  Thanks for helping. :)
