### ISSUE TITLE
Experience bar loops when repairing

### ISSUE THREAD

**Issue by Forecaster** [joshiejack/Mariculture#309]
When repairing something on the blacksmiths anvil, when the experience bar runs out when you have no levels left it fills up again. This appears to be repeatable indefinitely.

This means that you can keep repairing things even if you should have no experience left.

Tested with latest Mariculture build and Forge 10.13.4.1481 in an isolated instance.

**Comment by hanakocz** [comment]
Confirming the issue.

**Comment by LiteraryRecluse** [comment]
Yeah, I've noticed this as well.  I found it too convenient to say anything though. :P
