### ISSUE TITLE
Enchantments turning off when switching dimensions

### ISSUE THREAD

**Issue by LiteraryRecluse** [joshiejack/Mariculture#315]
I noticed a few days ago when switching dimensions my jewelry enchants "turn off," and the only way to re-activate them is to open my mirror and take off the jewelry and re-equip it.  

I noticed it when I was using a ring with Step up, and the ability stopped working when I jumped into the Nether.  It also reset when I jumped back into the Overworld, and did the same when I jump in and out of the Twilight Forest.

**Comment by Nathipha** [comment]
I can second that (version 1.2.4.2a, tested with "Step Up").
