### ISSUE TITLE
Blacksmith Hammer & Anvil doesn't work

### ISSUE THREAD

**Issue by Tsunayoshi** [joshiejack/Mariculture#317]
Hello,

a player on my server tryed to craft a golden ring. But the hammer doesn't work on the anvil.

To be sure it's not another mod I have reduced the mods to:
Mariculture-Deluxe-1.7.10-1.2.4.2a
Enchiridion 2-1.7.10-2.0.2a
forge-1.7.10-10.13.4.1492-1.7.10

and still it doesn't work.

**Comment by Tsyklop** [comment]
same problem
