### ISSUE TITLE
Paintbrush no longer picks up textures after using Extra Utilities Builder's Wand

### ISSUE THREAD

**Issue by Vashtiuthpisces** [joshiejack/Mariculture#319]
I was building with Mariculture custom cobble blocks, with the intention of painting them with the paintbrush. I decided to use the Extra Utilities Builder's Wand to speed up my build, but found that instead of placing the blocks in my inventory, it placed what looked like vanilla stone blocks, called "unnamed" Mariculture blocks. AFTER that occurred, any paintbrushes I create will no longer pick up textures, but instead will only paint the "unnamed" plain stone.

**Comment by Vashtiuthpisces** [comment]
I should note that I am using the FTB Monster 1.1.2 pack.

**Comment by joshiejack** [comment]
So you're using an obsolete pack.

**Comment by Vashtiuthpisces** [comment]
Thank you for responding. I had no idea. I'm new to both FTB and Mariculture and assumed Monster had an up to date version of your mod. I'll look into updating it on our server.

**Comment by joshiejack** [comment]
What. Monster is minecraft 1.6.4 and it isn't even using the last version of mariculture for that version of minecraft. It's VERY out of date on all the mods in it.
