### ISSUE TITLE
Air Pump Null Pointer Exception

### ISSUE THREAD

**Issue by lumine** [joshiejack/Mariculture#320]
I am playing the current version of the Regrowth mod pack from the Feed the Beast launcher.  Placing the air pump in single player and manually pumping it and swimming around causes the game to crash.  It has crashed about seven times and my world was corrupted and restored from backup twice.  The message is "A fatal error has occurred, this connection is terminated."  It kicks you out of single player and you end up at the multiplayer server screen instead of the single player saved games.

I found some people with the same issue within range of the Mariculture Air Pump:

http://forum.feed-the-beast.com/threads/1-7-10-regrowth-a-wip-hqm-pack-now-listed.57184/page-483

http://forum.feed-the-beast.com/threads/1-7-10-regrowth-a-wip-hqm-pack-now-listed.57184/page-370

https://mineyourmind.net/forum/threads/constant-fatal-error.7982/

https://mineyourmind.net/forum/threads/a-fatal-error-has-occurred-this-connection-is-terminated.10851/

java.lang.NullPointerException
at mariculture.core.network.PacketAirPump.onMessage(PacketAirPump.java:18) ~[PacketAirPump.class:?]
at mariculture.core.network.PacketAirPump.onMessage(PacketAirPump.java:9) ~[PacketAirPump.class:?]

**Comment by lumine** [comment]
My guess is that in PacketAirPump.java tile is null sometimes

if (tile instanceof TileAirPump) {

if (null != tile && tile instanceof TileAirPump) {

**Comment by ArmandVestibule** [comment]
I can also confirm that this issue is happening.  One of the players on my SMP server kept getting disconnected from the game with the same error.

It occured while the pump was active and while they were underwater without diving gear.  Their fml-client-lastest output is as follows upon disconnect:

java.lang.NullPointerException
	at mariculture.core.network.PacketAirPump.onMessage(PacketAirPump.java:18) ~[PacketAirPump.class:?]
	at mariculture.core.network.PacketAirPump.onMessage(PacketAirPump.java:9) ~[PacketAirPump.class:?]

**Comment by kotoroshinoto** [comment]
I have been getting this quite commonly. It seemed to become significantly worse with the erebus installed

it was happening to me, and I wasn't wearing diving gear

**Comment by kotoroshinoto** [comment]
might this be a duplicate: https://github.com/joshiejack/Mariculture/issues/314

**Comment by mindforger** [comment]
it always happens when i leave the area around the pump, this makes our world (MP server) unplayable

**Comment by mindforger** [comment]
has it been resolved ? because i can't see a new download ?!

**Comment by joshiejack** [comment]
I'm done with 1.7.10 which is why I closed this, but this particular issue was resolved in the 1.3.0 builds of Mariculture, which other than missing some docs and a couple textures was mostly complete http://joshiejack.uk:8080/view/1.7.10%20-%20Experimental/job/Mariculture%20-%20Experimental/

**Comment by mindforger** [comment]
uhh, love ya :D
