### ISSUE TITLE
[BUG] Ingot caster does not cast molten Metallurgy metals to ingot

### ISSUE THREAD

**Issue by hron84** [joshiejack/Mariculture#325]
See title. Metals coming from Metallurgy 4, smelted by TiCon smeltery are not casting to their ingot form.

Affected mods:

 - Mariculture-Deluxe-1.7.10-1.2.4.2a
 - Metallurgy-1.7.10-4.0.6.80
 - MetallurgyCore-1.7.10-4.0.4.18
 - TConstruct-1.7.10-1.8.7

**Comment by joshiejack** [comment]
This wouldn't have been a bug. It's that they wouldn't have had recipes. In theory in the 1.3.0 version I added support for automatically adding the recipes. But that was never officially released but eh, it still works. But either way I am done with 1.7.10, and I won't have this in the 1.8+ versions anyways, so closing.

**Comment by hron84** [comment]
@joshiejack it means 1.8+ versions will lack ingot caster and these things? If yes, I'd be sad...

**Comment by joshiejack** [comment]
They don't really fit the theme of what the mod was meant to be. If I was to keep the ingot caster and likes, it would be in it's own mod.

**Comment by hron84** [comment]
It does except the ingot caster. Pouring four ingots at once is a thing that Tinkers can't do. Could you keep this as a Tinker's addon (only activate it when TiCon is installed and take TiCon recipes for it)? I really, really loved this stuff.
