### ISSUE TITLE
Mariculture and harvest craft compatibility

### ISSUE THREAD

**Issue by 31trainman** [joshiejack/Mariculture#331]
I see this appear in my multimc console when starting my custom modpack. 
 [Mariculture]: Something went wrong when initializing HarvestCraft Plugin

multimc version: 0.4.7 64bit
Forge 1517
-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Mac OS X (x86_64) version 10.11
	Java Version: 1.8.0_60, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2777495368 bytes (2648 MB) / 3087007744 bytes (2944 MB) up to 4772593664 bytes (4551 MB)
	JVM Flags: 2 total; -Xms3072m -Xmx5120m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '2.1 NVIDIA-10.0.37 310.90.10.05b12' Renderer: 'NVIDIA GeForce GT 330M OpenGL Engine'
Mods:
  CMIP-1.7.10-1.0Beta.23
  DragonAPI 1.7.10 V9b
  ElecCore-1.7.10-1.4.175
  ReactorCraft 1.7.10 V9b
  RotaryCraft 1.7.10 V9b
  AdvancedSolarPanel-1.7.10-3.5.1
  AOBD-2.8.4
  AOBDBB-1.0.6
  AppleMilkTea2-1.7.10_2.8k
  appliedenergistics2-rv3-alpha-9
  AsieLib-1.7.10-0.4.4
  BiblioCraft[v1.11.4][MC1.7.10]
  BiblioWoods[Natura][v1.5]
  BigDoors-1.7.10-1.0.0
  BigReactors-0.4.3A
  browncoalmod-1.2.1
  buildcraft-7.1.12
  BunkerMod-1.1
  Carpenter's Blocks v3.3.7 - MC 1.7.10
  PFAA-1.7.10-0.2.27
  Chisel2-2.5.1.44
  ChiselTones-1.7.10-1.0-3
  CodeChickenCore-1.7.10-1.0.7.47-universal
  CoFHCore-[1.7.10]3.0.3-303
  ComputerCraft1.74
  Computronics-1.7.10-1.5.9
  CookieCore-1.7.10-1.4.0-11
  CustomOreGen-1.7.10-1.2.21
  deepresonance-1.1.0beta1
  DenseEBOres-1.7.10-1.1
  denseores-1.6.2
  Draconic-Evolution-1.7.10-1.0.2-Snapshot_4
  ElectricalAge_BETA-1.10_r50
  Electrolysm_Core-1.7.10-1.2.42a
  Enchiridion-1.7.X-1.2b
  EnderIO-1.7.10-2.3.0.417_beta
  EnderZoo-1.7.10-1.0.15.32
  EnderCore-1.7.10-0.2.0.30_beta
  Enhanced Biomes 2.5 for MC 1.7.10
  EnviroMine-1.3.122
  BrandonsCore-1.0.0.8
  ExtraCells-1.7.10-2.2.73b129
  extrautilities-1.2.11
  ExtraTiC-1.7.10-1.4.5
  Farseek-1.0.10
  fastcraft-1.21
  FlenixCitiesCore_[1.7.10]-0.11.0-b67
  FlenixCitiesFood_[1.7.10]-0.5
  FlenixCitiesResearch_[1.7.10]-0.4
  FlenixRoads_[1.7.10]-0.7
  FrameCompanion-1.1
  GardenStuff-1.7.10-1.6.8
  Guide-API-1.7.10-1.0.1-20
  HydCraft-1.7.10-2.1.242-universal
  ImmersiveEngineering-0.6.0
  immersiveintegration-0.6.0
  IGW-Mod-1.7.10-1.1.11-32-universal
  industrialcraft-2-2.2.791-experimental
  InventoryTweaks-1.59-dev-152
  IvToolkit-1.2
  k4lib-1.7.10-0.1.55-universal
  logisticspipes-0.9.3.68
  ModularPowersuits-0.11.0.283
  magneticraft-0.5.1
  malisisdoors-1.7.10-1.10
  malisisadvert-1.7.10-0.4.2
  malisiscore-1.7.10-0.12.9
  Mantle-1.7.10-0.3.2b
  Mariculture-Deluxe-1.7.10-1.2.4.2a
  MatterOverdrive-1.7.10-0.4.0
  mcjtylib-1.7.0
  Mekanism-1.7.10-8.1.7.252
  MekanismGenerators-1.7.10-8.1.7.252
  MekanismTools-1.7.10-8.1.7.252
  Metallurgy-1.7.10-4.0.8.97
  MetallurgyCore-1.7.10-4.0.4.18
  Minechem-1.7.10-5.0.5.406
  MineFactoryReloaded-[1.7.10]2.8.0-104
  natura-1.7.10-2.2.1a2
  neiaddons-1.12.14.40-mc1.7.10
  NEIIntegration-MC1.7.10-1.0.13
  NotEnoughResources-1.7.10-0.1.0.106
  NotEnoughItems-1.7.10-1.0.5.118-universal
  IC2NuclearControl-2.3.1a-Butt
  NuclearCraft-0.0.1.5--1.7.10
  Numina-0.4.0.131
  OpenBlocks-1.7.10-1.4.4
  OpenComputers-MC1.7.10-1.5.19.37-universal
  OpenModsLib-1.7.10-0.8
  OpenPeripheral-1.7.10-AIO-5
  Pam's HarvestCraft 1.7.10k
  PlanetguyLib-1.9.1
  PneumaticCraft-1.7.10-1.11.19-141-universal
  ProjectBlue-1.1.4-mc1.7.10
  ProjectRed-1.7.10-4.7.0pre9.92-Compat
  ProjectRed-1.7.10-4.7.0pre9.92-Base
  ProjectRed-1.7.10-4.7.0pre9.92-World
  ProjectRed-1.7.10-4.7.0pre9.92-Fabrication
  ProjectRed-1.7.10-4.7.0pre9.92-Lighting
  ProjectRed-1.7.10-4.7.0pre9.92-Integration
  qCraft1.2
  QuantumFlux-1.7.10-1.3.2-b4
  Railcraft_1.7.10-9.8.0.0
  RTG-1.7.10-0.0.15
  Redstonic-v1.4.11
  RemainInMotion-2.8.8
  rftools-4.01
  ShipsAddon-1.7.10-1.0.2a
  shipsMod-v1.7.10-1.0.4
  Streams-0.1.6
  ThermalDynamics-[1.7.10]1.1.0-161
  ThermalExpansion-[1.7.10]4.0.3B1-218
  ThermalFoundation-[1.7.10]1.2.0-102
  TiCTooltips-mc1.7.10-1.2.5
  TConstruct-1.7.10-1.8.8
  TSteelworks-1.7.10-1.1.1-17
  Waila-1.5.10_1.7.10
  WailaHarvestability-mc1.7.x-1.1.2
  Wawla-1.3.2-1.7.10
  WR-CBE-1.7.10-1.4.1.9-universal
  YeGamolChattels-1.1.2
  zettaindustries-1.1-105
  Zora no Densha_v0.7.3_MC 1.7.10
  Zora no Densha Track Pack - Default
  Ztones-1.7.10-2.2.1

**Comment by joshiejack** [comment]
I never updated the harvestcraft plugin for new versions and eventually just removed it anyway, so that was just safely ignored.
