### ISSUE TITLE
Mariculture fluid tanks cause a client crash when Liquid XP is stored in them.

### ISSUE THREAD

**Issue by xannor** [joshiejack/Mariculture#332]
This seems to be an issue between Mariculture, Immibis Liquid XP, and da3dsoul's Additional Buidcraft objects. The crash only happens if liquid xp is stored in Mariculture tanks, other tanks (buildcraft, railcraft, etc) that I have tested with work correctly.
[crash-2015-11-15_17.19.51-client.txt](https://github.com/joshiejack/Mariculture/files/35043/crash-2015-11-15_17.19.51-client.txt)

**Comment by catzs** [comment]
What pack is this?
Try reporting this to the other developers, joshiejack seems to be gone.

**Comment by xannor** [comment]
its my personal modlist, and since the issue is only with mariculture tanks reporting it to the other developers would not yield many results either. It luckily is minor to work around, i.e. don't use the mariculture tanks with immibus liquid xp, so it is not critical. If Joshie comes back or another picks this up they have some info to try and fix it with, if not then when this mod goes stale it would be insignificant.
