### ISSUE TITLE
NEI Recipe Check Crash

### ISSUE THREAD

**Issue by SirWoofie** [joshiejack/Mariculture#333]
Anything I recipe check crashes me, ChickenBones wants me to inform you about this problem.
Link to the issue I posted in NEI's issues:
https://github.com/Chicken-Bones/NotEnoughItems/issues/303#issuecomment-158735218
For now, I guess I will downgrade to a "Recipe Checkable" Mariculture version.

**Comment by joshiejack** [comment]
Would have been helfpul if you'd told me the version you were using but either way. 1.7 is done, and JEI for the future \o/.
