### ISSUE TITLE
XP and OB\EIO

### ISSUE THREAD

**Issue by zHawky** [joshiejack/Mariculture#336]
Hi joshie, did you know problem around xp in 1.7.10v?
When im got hammer and went to repair tool\weapon im can infinite repair tools while have only 1 level, xp line goes always backward.. and then if im stand over xp drainer\xp obelisk i can get over 50 cheaty levels. its definitely bug, while in 1.6.4v this is not present.

**Comment by joshiejack** [comment]
Yeah. Either way done with 1.7 version, so this can stay ;p.

**Comment by zHawky** [comment]
Wow, i'll be waiting for this.
