### ISSUE TITLE
Logs don't even show up in left-side slots of Auto-Dictionary

### ISSUE THREAD

**Issue by MauveCloud** [joshiejack/Mariculture#337]
Clicking with a log has no effect in the left-side slots of the Auto-Dictionary, as if the logs had no ore dictionary entry (even though NEI Integration confirms that they do with my current set of mods)
Planks and sticks appear in the left slots, and indicate that they're blacklisted, but when I click with a log selected, the slot remains stubbornly blank.

**Comment by joshiejack** [comment]
By default they're blacklisted, no idea why wouldn't display that. Either way, done with 1.7 so closing.
