### ISSUE TITLE
Severe graphical glitches when viewing some pages of Mariculture books

### ISSUE THREAD

**Issue by MauveCloud** [joshiejack/Mariculture#338]
Sometimes recipes just flicker with barely-noticeable artifacts around the edges, but other pages have worse issues: the right page might not stay visible, recipes might flicker in the wrong location, and there might even be an intermittent x-ray effect.  See attached images for examples.

Complete list of mods I'm using (in case one is incompatible):
```
advancedgenetics-1.7.10-1.5.9.jar
appliedenergistics2-rv2-stable-10.jar
Aroma1997Core-1.7.10-1.0.2.16.jar
Batty's Coordinates PLUS Mod for Forge-1.7.10_1.6.0.jar
bdlib-1.9.3.107-mc1.7.10.jar
BedrockLayer_1.7.2-v1.0.9.jar
BetterChests-1.7.10-1.1.1.9.jar
buildcraft-7.1.14.jar
buildcraft-compat-7.1.3.jar
Carpenter's Blocks v3.3.8_dev_r4 - MC 1.7.10.jar
CodeChickenCore-1.7.10-1.0.7.47-universal.jar
craftnstar-1.7.10-0.2.1.jar
custommobdrops-1.7.10-1.1.jar
CustomOreGen-1.7.10-1.2.24.jar
Enchiridion-1.7.X-1.2b.jar
EnderCore-1.7.10-0.2.0.30_beta.jar
ExtraCells-1.7.10-2.2.73b129.jar
forestry_1.7.10-4.2.4.873-unstable.jar
GregsLighting-1.11.2-mc1.7.10.jar
gregtech-5.09.19.jar
GTTweaker-1.7.10-1.0.9.jar
IGW-Mod-1.7.10-1.1.11-32-universal.jar
industrialcraft-2-2.2.810-experimental.jar
InventoryTweaks-1.59-dev-152.jar
Jabba-1.2.1a_1.7.10.jar
journeymap-1.7.10-5.1.0-unlimited.jar
Mariculture-Deluxe-1.7.10-1.2.4.2a.jar
MCA-1.7.10-5.1.0.1-universal.jar
MineTweaker3-1.7.10-3.0.9C.jar
mod_ControlPack_f9caf9a2d42a843dc380ca8e8bb6cea249f6f094_mc1.7.10.litemod
MouseTweaks-2.4.4-mc1.7.10.jar
neiaddons-1.12.14.40-mc1.7.10.jar
NEIIntegration-MC1.7.10-1.0.13.jar
NotEnoughItems-1.7.10-1.0.5.118-universal.jar
OptiFine_1.7.10_HD_U_C1.jar
PFAA-1.7.10-0.2.27.jar
RadixCore-1.7.10-2.1.1-universal.jar
Railcraft_1.7.10-9.8.0.0.jar
Squeedometer-mc1.7.x-1.0.3.jar
VillageInfoSSP-1.7.10-2.1.jar
Waila-1.5.10_1.7.10.jar
WAILAPlugins-MC1.7.10-0.2.0-23.jar
Wawla-1.3.2-1.7.10.jar
[1.7.10]Treecapitator-universal-2.0.4.jar
[1.7.10]WorldStateCheckpoints-client-1.7.10.r03.jar
[1.7.2] ChickenShed (v1.1.3).jar
1.7.10\CodeChickenLib-1.7.10-1.1.3.138-universal.jar
1.7.10\[1.7.10]bspkrsCore-universal-6.16.jar
carpentersblocks\CarpentersBlocksCachedResources.zip
ic2\EJML-core-0.26.jar
```

In case it matters, I'm also using Sphax PureBDCraft texture packs for most of my mods (that have textures to replace), but hadn't downloaded the patch for Mariculture, which was for v1.2.1e for MC 1.6.4

![2016-01-11_08 27 52](https://cloud.githubusercontent.com/assets/8942955/12239968/15ce3cc8-b840-11e5-8af2-b373685c5902.png)
![2016-01-11_08 28 55](https://cloud.githubusercontent.com/assets/8942955/12239972/15d840a6-b840-11e5-834d-0b75e5ccf171.png)
![2016-01-11_08 29 52](https://cloud.githubusercontent.com/assets/8942955/12239969/15d0e388-b840-11e5-8a21-94a44e321a6a.png)
![2016-01-11_08 30 16](https://cloud.githubusercontent.com/assets/8942955/12239970/15d1abba-b840-11e5-8c27-7308bb4905de.png)
![2016-01-11_08 30 34](https://cloud.githubusercontent.com/assets/8942955/12239971/15d2655a-b840-11e5-8d96-58cbed026631.png)

**Comment by joshiejack** [comment]
Absolutely no clue, and if anything this would have been an enchiridion issue as the books were all handled by it. I was in the process of updating the books to the enchiridion 2 format, but never finished it, which is the main reason the latest mariculture version was never properly finished.
