### ISSUE TITLE
Feature Request: blacklist suffixes in Auto-Dictionary

### ISSUE THREAD

**Issue by MauveCloud** [joshiejack/Mariculture#339]
GregTech has some ore dictionary entries ending in "AnyIron" or "AnyCopper", used in recipes where it doesn't matter whether the iron is just "iron", wrought iron (normally requires furnacing iron nuggets or arc-furnacing iron ingots to obtain), or pig iron (normally requires Tinkers' Construct to obtain), or whether the copper is annealed (which normally requires the arc furnace).  However, wrought iron and pig iron tools have 50% higher durability, pig/wrought iron ingots can be converted to steel ingots in an Electric Blast Furnace more efficiently than plain iron, and annealed copper cables have lower cable loss than regular cable, so it would be unbalanced to be able to convert them at no EU cost in an Auto-Dictionary, but it would be a bit impractical to separately blacklist all the item types for these materials.

**Comment by joshiejack** [comment]
I'm going to close this, while a nice suggestion I am done with the 1.7.10 version, and I don't plan to readd the auto-dictionary in the 1.8 versions where i plan to refocus the mod, as it doesn't fit the theme. (Plenty of mods that do it anyway).
