### ISSUE TITLE
fps drop when opening the Crucible Furnace

### ISSUE THREAD

**Issue by johnfg12** [joshiejack/Mariculture#340]
https://www.youtube.com/watch?v=-kM1r4_qpYY&feature=youtu.be

we have noticed that the crucible furnace badly effects fps on all versions in the demo above 
version Mariculture Deluxe 1.7.10 1.2.4.2a whitch to my recorded is the latest version

**Comment by joshiejack** [comment]
Closing as 1.7 mariculture is done, technically the latest dev versions were stable enough and may have fixed it, they just had missing fish textures and docs. I've no idea if this was fixed in them though.
