### ISSUE TITLE
GregTech aluminium compatiblity issue

### ISSUE THREAD

**Issue by MauveCloud** [joshiejack/Mariculture#341]
GregTech unifies Mariculture aluminium ingots to GregTech aluminium ingots.  For most other mods, the Unification config would allow me to change the unification target to a given mod's ingot type instead, but apparently Mariculture aluminium ingots aren't recognized as valid targets.  Also, even when I use Minetweaker to mirror ingotAluminium and ingotAluminum, GregTech aluminium ingots aren't usable in Mariculture recipes, even though GregTech titanium ingots and magnesium ingots are.  I can set up Minetweaker recipes for the items I'm interested in, but I shouldn't have to.

**Comment by joshiejack** [comment]
The standard set by the community for the spelling was ingotAluminum. Being british I spell it the other way, but that is what everyone settled on, so it's what I use. It's what I ask for in my recipes. Why greg decided to try and get everyone to use the other spelling in the ore dictionary is beyond me, considering how much he'd moan about people not using the ore dictionary correctly. It's not my fault he didn't want to follow the standard. Which causes this issue. And no you shouldn't have to. However it is still not my issue.

**Comment by MauveCloud** [comment]
Then why didn't mirroring the ore dictionary entries, so that GT aluminium ingots show as both ingotAluminium and ingotAluminum (according to NEI Integration) work?

**Comment by joshiejack** [comment]
No clue. I've used other mods aluminium to make things before.

**Comment by MauveCloud** [comment]
Some further experimentation, and apparently Minetweaker's "mirror" function doesn't work that well.  Neither
<ore:ingotAluminum>.mirror(<ore:ingotAluminium>);
nor
<ore:ingotAluminium>.mirror(<ore:ingotAluminum>);
worked, but
<ore:ingotAluminum>.addAll(<ore:ingotAluminium>);
allows me to use GT aluminium ingots in Mariculture recipes.
