### ISSUE TITLE
[v1.3.0-23] java.lang.NoSuchFieldError: manaPetal

### ISSUE THREAD

**Issue by Kiyaku** [joshiejack/Mariculture#343]
Version: Mariculture-Deluxe-1.7.10-1.3.0-23

Crash log: http://pastebin.com/0itqs4iR

**Comment by joshiejack** [comment]
Did things change in newer versions of botania, i don't actually have a dev space setup for mariculture anymore, so idk what's missing

**Comment by Kiyaku** [comment]
I'll use my little modding knowledge and check real quick heh, maybe the name changed for it.

**Comment by joshiejack** [comment]
Ahh looks like i was calling it directly out of laziness, probably moved it, should have probably been grabbing it from the registry.

**Comment by joshiejack** [comment]
Should be fixed
