### ISSUE TITLE
WorldGen compatability

### ISSUE THREAD

**Issue by Matryoshika** [joshiejack/Mariculture#355]
**Question, not issue**

Hello Joshie / Whoever reads this!
I've currently made my own small mod that amongst other things, makes the Overworld generate as converted Nether (same shape, but with stone dirt etc, not netherrack)

As the base of this WorldType uses code akin to the Nether's, it errored out on your WorldEventHandler#onReplaceBiomeBlocks. As this is an issue on MY end, I decided to just simply play around the issue, and have mariculture work as if it was an addon, for my mod. This means I created my own classes implementing IWorldGenerator, get viable spawn-locations, and then spawn your blocks manually.
Now however, I'm facing an issue that I have gone over numerous times, but keep getting the same crash. (Exception ticking world)
My (appropriately named) DirtyOysterGen.class is [here](http://pastebin.com/VYHkHEYR).
Crash-report is [here](http://pastebin.com/iyeLsuJK).

I'm just asking if I've missed something obvious, or if just my own worldgen based on the Nether's is the culprit behind everything.

**Comment by joshiejack** [comment]
My only guess is that perhaps the tile is null because the oyster doesn't stay there? I'm not sure when things get called but oysters pop off if the block above them isn't water. Here's mine for reference:

https://github.com/joshiejack/Mariculture/blob/1.7.10-1.3.0/src/main/java/mariculture/core/handlers/WorldGenHandler.java#L68

**Comment by Matryoshika** [comment]
>_> That is likely it, yes.
I've gone over your Oyster generation, and made sure to keep roughly the same code execution.
Though I missed the y+1 == water check. It did work for some oysters, which is likely what made me miss it. They did not have water on top of them, but were still placed. Probably because they hadn't been ticked (I am currently (as of a few hours now) forcing a new tile at their location, thus forcing them to tick) 

Going to test it out with a proper y+1 check!

Thank you joshie :smiley:

**Comment by Matryoshika** [comment]
Yep, no more crashes. 10 min of forced worldgen, and not a single issue any more :smiley: 

Once again, thank you!
