### ISSUE TITLE
Fatal Error Connection Lost with PacketAirPump

### ISSUE THREAD

**Issue by shortybsd** [joshiejack/Mariculture#356]
Mariculture: 1.2.4.2a
Enchiridion: 1.2b
Forge: 1.7.10-Forge10.13.4.1566-1.7.10
All the users on my server are getting random client crashes/disconnects. I can't do anything specific to reproduce this error. I do have 2 air pumps nearby (50 to 100 blocks away). Their client says fatal error lost connection. We can reconnect and it will do it randomly until we move from the area. Gotta love NPE's lol. Here is the error log from the client itself: 
http://pastebin.com/tBT0tYy7

**Comment by joshiejack** [comment]
Try the 1.3.0 alphas on curseforge. I'm done with 1.7.10, but those I believe have this issue fixed. (It's listed as alpha because i'm not working on it, (just prs from other people). Not because it's unstable
