### ISSUE TITLE
Mariculture Fish Breeding of Stargazer's cause the server JVM to OOM very quickly

### ISSUE THREAD

**Issue by vagaprime** [joshiejack/Mariculture#357]
Someone has started fish breeding on a server running my pack. The server admin has reported the problem to me in my github. I know that the mod is not being worked on for 1.7.10 but maybe someone can find the problem and submit a pull request with a fix.

https://github.com/vagaprime/MageTech-Gate/issues/24

**Comment by joshiejack** [comment]
Hope someone else kindly finds the time, Just looking at my terrible code really makes me cringe. Learnt so much since I wrote the terrors within 😰

**Comment by vagaprime** [comment]
lol I am not sure if that was a good thing or a bad thing.

**Comment by vagaprime** [comment]
any suggested work around for this till then?

**Comment by joshiejack** [comment]
Can't think of anything honestly, just have to forbid it :/

**Comment by vagaprime** [comment]
I think the person working on fish said that the Stargazer is needed to progress

**Comment by joshiejack** [comment]
Could always give them what they're trying to create?

**Comment by joshiejack** [comment]
Tbh I can be lazy and just comment out the code

**Comment by joshiejack** [comment]
@vagaprime Let me know if this works, if so ill upload it to curse, just disables the effect thats supposed to happen, stopping spawns so shouldnt be a big deal

http://joshiejack.uk/view/All/job/Mariculture%20-%201.7.10%20-%20Experimental/6/

**Comment by vagaprime** [comment]
sure I can get it tested. I will send a version of my pack with that version to the player that knows more about the fish breeding then me.

**Comment by vagaprime** [comment]
Ok the player tested the build and the problem seems to be fixed.

**Comment by joshiejack** [comment]
Thanks :)
